# Generated by Django 2.1.5 on 2019-02-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190209_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpost',
            name='data',
        ),
        migrations.AddField(
            model_name='formpost',
            name='data',
            field=models.ManyToManyField(blank=True, null=True, to='api.FormData'),
        ),
    ]
