# Generated by Django 2.1.5 on 2019-02-09 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190209_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpost',
            name='data',
        ),
        migrations.AddField(
            model_name='formdata',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.FormPost'),
        ),
    ]
