# Generated by Django 2.1.7 on 2019-07-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190720_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='adhaarNo',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='emergencyContact',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
