# Generated by Django 2.2.4 on 2019-08-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190805_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='education',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
