# Generated by Django 2.2.4 on 2019-08-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190806_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='officeAddress',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
