# Generated by Django 2.2.4 on 2019-08-05 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190806_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='donationDate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 8, 6, 3, 13, 24, 971474), null=True),
        ),
    ]
