# Generated by Django 2.2.1 on 2019-08-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190806_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='donationDate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
