# Generated by Django 2.2.1 on 2019-07-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190728_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='channelName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wstokens',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
