# Generated by Django 2.2.1 on 2019-07-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190728_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logs',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='channelName',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
