# Generated by Django 2.2.4 on 2019-08-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190806_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='emergencyContact',
        ),
        migrations.AddField(
            model_name='group',
            name='ishidden',
            field=models.BooleanField(default=False),
        ),
    ]
