# Generated by Django 2.2.1 on 2019-08-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_logs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formpost',
            old_name='timestamp',
            new_name='time',
        ),
    ]
