# Generated by Django 2.2.1 on 2019-08-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190810_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profilePic',
            field=models.ImageField(blank=True, default='media/avatar.png', null=True, upload_to='media/'),
        ),
    ]
